version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      ## reason: "Temporary compatibility issues. Revisit after migration to Python 3.13."
      - dependency-name: "playwright"
    labels:
      - "pip-dependencies"