service: odds-harvester

provider:
  name: aws
  architecture: arm64
  region: eu-west-3
  versionFunctions: false
  ecr:
    images:
      playwright_python_arm64:
        path: ./
        file: Dockerfile
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
          - s3:DeleteObject
        Resource: "arn:aws:s3:::odds-portal-scrapped-odds-cad8822c179f12cg/*"

functions:
  scanAndStoreOddsPortalDataV2:
    image:
      name: playwright_python_arm64
    timeout: 360 # seconds
    memorySize: 2048 # mb
    description: Retrieve and store sports betting odds
    events:
      - eventBridge:
        schedule: rate(2 hours)

package:
  individually: true
  patterns:
    - "!node_modules/**"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    strip: false
    noDeploy: ['boto3']